---
apiVersion: v1
kind: Namespace
metadata:
  name: $USER
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trainer-crb
  namespace: $USER
roleRef:   
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default    
  namespace: train
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding 
metadata:
  name: $USER-rb
  namespace: $USER
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: $USER
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: $USER-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: default
  namespace: $USER
---
apiVersion: v1
kind: Service
metadata:
  name: $USER-shell
  namespace: $USER
  labels:
    app: shell
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: shell
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $USER-shell-deploy
  namespace: $USER
spec:
  selector:
    matchLabels:
      app: shell
  replicas: 1
  template:
    metadata:
      labels:
        app: shell
    spec:
      containers:
      - image: acend/alpine-sshd
        imagePullPolicy: Always
        name: sshd
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: STUDENT
          value: "$USER"
        ports:
        - containerPort: 22
          protocol: TCP
      - image: docker:18.09.9-dind
        imagePullPolicy: Always
        name: dind
        ports:
        - containerPort: 2375
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities: {}
          privileged: true
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        readinessProbe:
          tcpSocket:
            port: 2375
          initialDelaySeconds: 2
          timeoutSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 2375
          initialDelaySeconds: 5
          timeoutSeconds: 10
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
