---
apiVersion: v1
kind: Namespace
metadata:
  name: $STUDENT
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding 
metadata:
  name: $STUDENT-rb
  namespace: $STUDENT
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: $STUDENT
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: $STUDENT-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: default
  namespace: $STUDENT
---
apiVersion: v1
kind: Service
metadata:
  name: $STUDENT-theia-svc
  namespace: $STUDENT
  labels:
    app: theia
spec:
  ports:
  - name: web
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: theia
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $STUDENT-theia-deploy
  namespace: $STUDENT
spec:
  selector:
    matchLabels:
      app: theia
  replicas: 1
  template:
    metadata:
      labels:
        app: theia
    spec:
      containers:
      - image: acend/theia
        imagePullPolicy: Always
        name: theia
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 50Mi
        env:
        - name: STUDENT
          value: "$STUDENT"
        ports:
        - containerPort: 3000
          protocol: TCP
      - image: docker:18.09.9-dind
        imagePullPolicy: Always
        name: dind
        ports:
        - containerPort: 2375
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities: {}
          privileged: true
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        readinessProbe:
          tcpSocket:
            port: 2375
          initialDelaySeconds: 2
          timeoutSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 2375
          initialDelaySeconds: 5
          timeoutSeconds: 10
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: theia-ing
  namespace: $STUDENT
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: basic-auth
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - $STUDENT.theia.acend.ch
    secretName: theia-tls
  rules:
  - host: $STUDENT.theia.acend.ch
    http:
      paths:
      - path: /
        backend:
          serviceName: $STUDENT-theia-svc
          servicePort: 3000
