# Default values for webshell.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1


student: "test"


rbac:
  create: false

reset:
  enabled: true
  schedule: 0 */1 * * *

ingress:
  enabled: true
  className: ""
  annotations: 
    kubernetes.io/ingress.class: nginx-public
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-type: "basic"
    nginx.ingress.kubernetes.io/auth-secret: "basic-auth"
    

  hosts:
    - host: webshell-demo.training.acend.ch
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: acend-wildcard
      hosts:
        - webshell-demo.training.acend.ch

