{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  name: view-nodes-{{ .Values.user }}-crb
  labels:
    {{- include "webshell.labels" . | nindent 4 }}
subjects:
- kind: User
  name: system:serviceaccount:{{ .Release.Namespace }}:{{ include "webshell.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: acend-webshell-{{ .Values.user }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}