---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding 
metadata:
  name: admin-rb
  labels:
    {{- include "webshell.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ include "webshell.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}