{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding 
metadata:
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  name: admin-rb
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "webshell.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: {{ include "webshell.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}