{{- if not .Values.openshiftOauthProxy.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  labels:
    {{- include "webshell.labels" . | nindent 4 }}
type: Opaque
data:
  auth: {{ (htpasswd .Values.user .Values.password) | b64enc | quote }}
{{- end -}}
