apiVersion: v1
kind: Service
metadata:
  name: {{ include "webshell.fullname" . }}
  labels:
    {{- include "webshell.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: web
  selector:
    {{- include "webshell.selectorLabels" . | nindent 4 }}
