apiVersion: v1
kind: Service
metadata:
  name: {{ include "webshell.fullname" . }}
  annotations:
    {{- if .Values.openshift }}
    service.beta.openshift.io/serving-cert-secret-name: webshell-proxy-tls
    {{- end }}
  labels:
    {{- include "webshell.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if .Values.openshift }}
      targetPort: 8888
      {{- else }}
      targetPort: 3000
      {{- end }}
      protocol: TCP
      name: web
  selector:
    {{- include "webshell.selectorLabels" . | nindent 4 }}
