# changeme 
# Change the following parts to your current installation
# - Helm Target Namespace
# - Repository: you might need to change the name of your repository, depending on the choosen name
# - Secrets
#   - QUAYIO_API_TOKEN is needed for house keeping and removing old tagged images
#   - KUBECONFIG_TEST content of the Kubeconfig File, Account must have access to the k8s namespace. It's used in the helm steps
name: PRCleanup
on:
  pull_request:
    types: [closed]

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Delete Tags on Quay
        id: delete_tags
        env:
          PR_NUMBER: '${{ github.event.pull_request.number }}'
          QUAYIO_API_TOKEN: '${{ secrets.QUAYIO_API_TOKEN }}'
        run: |
          curl -X DELETE -H "Authorization: Bearer ${QUAYIO_API_TOKEN}" https://quay.io/api/v1/repository/acend/theia/tag/pr-${PR_NUMBER}{,-puzzle}
