# Default values for webshell.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

student: "student1"
password: "changeme"

openshift: true

image:
  pullPolicy: IfNotPresent

theia:
  image:
    repository: quay.io/acend/theia
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 50Mi
  securityContext: {}
  persistence:
    enabled: false
    pvcsize: 1Gi
    storageclass: cloudscale-volume-ssd

init:
  image:
    repository: quay.io/prometheus/busybox
    tag: latest
  command:
  - sh
  - -c
  - echo Welcome to the acend theia ide > /home/project/welcome

dind:
  enabled: false
  image:
    repository: docker
    tag: 20.10.12-dind
  resources: {}
  persistence:
    enabled: false
    pvcsize: 50Gi
    storageclass: cloudscale-volume-ssd

openshiftOauthProxy:
  image:
    repository: registry.redhat.io/openshift4/ose-oauth-proxy
    tag: v4.9

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1001

rbac:
  create: true

reset:
  enabled: false
  schedule: 0 */1 * * *

service:
  type: ClusterIP
  port: 8888

updateStrategy:
  type: RollingUpdate

ingress:
  enabled: true
  className: ""
  annotations:
    route.openshift.io/termination: reencrypt
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: webshell-test.ocp.aws.puzzle.ch
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #- secretName: webshell-tls
  #  hosts:
  #    - webshell-test.ocp-staging.cloudscale.puzzle.ch

nodeSelector: {}

tolerations: []

affinity: {}
