# Default values for webshell.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1


student: "student1"
password: "changeme"

image:
  pullPolicy: IfNotPresent

theia:
  image:
    repository: quay.io/acend/theia
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  resources: 
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 50Mi
  securityContext: {}
  persistence:
    enabled: false
    pvcsize: 1Gi
    storageclass: cloudscale-volume-bulk

init:
  image:
    repository: busybox
    tag: latest

dind:
  enabled: true
  image:
    repository: docker
    tag: 20.10.11-dind
  resources: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1001

rbac:
  create: true

reset:
  enabled: false
  schedule: 0 */1 * * *

service:
  type: ClusterIP
  port: 3000

updateStrategy:
  type: RollingUpdate

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nodeSelector: {}

tolerations: []

affinity: {}
